// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/rdimidov/kvstore/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockrepository creates a new instance of mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepository {
	mock := &mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepository is an autogenerated mock type for the repository type
type mockrepository struct {
	mock.Mock
}

type mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepository) EXPECT() *mockrepository_Expecter {
	return &mockrepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockrepository
func (_mock *mockrepository) Delete(ctx context.Context, key domain.Key) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockrepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *mockrepository_Expecter) Delete(ctx interface{}, key interface{}) *mockrepository_Delete_Call {
	return &mockrepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *mockrepository_Delete_Call) Run(run func(ctx context.Context, key domain.Key)) *mockrepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key))
	})
	return _c
}

func (_c *mockrepository_Delete_Call) Return(err error) *mockrepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key domain.Key) error) *mockrepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockrepository
func (_mock *mockrepository) Get(ctx context.Context, key domain.Key) (*domain.Entry, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) (*domain.Entry, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) *domain.Entry); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Key) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockrepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *mockrepository_Expecter) Get(ctx interface{}, key interface{}) *mockrepository_Get_Call {
	return &mockrepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *mockrepository_Get_Call) Run(run func(ctx context.Context, key domain.Key)) *mockrepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key))
	})
	return _c
}

func (_c *mockrepository_Get_Call) Return(entry *domain.Entry, err error) *mockrepository_Get_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *mockrepository_Get_Call) RunAndReturn(run func(ctx context.Context, key domain.Key) (*domain.Entry, error)) *mockrepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type mockrepository
func (_mock *mockrepository) Set(ctx context.Context, key domain.Key, value domain.Value) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key, domain.Value) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockrepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *mockrepository_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *mockrepository_Set_Call {
	return &mockrepository_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *mockrepository_Set_Call) Run(run func(ctx context.Context, key domain.Key, value domain.Value)) *mockrepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key), args[2].(domain.Value))
	})
	return _c
}

func (_c *mockrepository_Set_Call) Return(err error) *mockrepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepository_Set_Call) RunAndReturn(run func(ctx context.Context, key domain.Key, value domain.Value) error) *mockrepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// newMockcompute creates a new instance of mockcompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcompute {
	mock := &mockcompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcompute is an autogenerated mock type for the compute type
type mockcompute struct {
	mock.Mock
}

type mockcompute_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcompute) EXPECT() *mockcompute_Expecter {
	return &mockcompute_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockcompute
func (_mock *mockcompute) Delete(ctx context.Context, key domain.Key) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcompute_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockcompute_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *mockcompute_Expecter) Delete(ctx interface{}, key interface{}) *mockcompute_Delete_Call {
	return &mockcompute_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *mockcompute_Delete_Call) Run(run func(ctx context.Context, key domain.Key)) *mockcompute_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key))
	})
	return _c
}

func (_c *mockcompute_Delete_Call) Return(err error) *mockcompute_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcompute_Delete_Call) RunAndReturn(run func(ctx context.Context, key domain.Key) error) *mockcompute_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockcompute
func (_mock *mockcompute) Get(ctx context.Context, key domain.Key) (*domain.Entry, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) (*domain.Entry, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key) *domain.Entry); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Key) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcompute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockcompute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *mockcompute_Expecter) Get(ctx interface{}, key interface{}) *mockcompute_Get_Call {
	return &mockcompute_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *mockcompute_Get_Call) Run(run func(ctx context.Context, key domain.Key)) *mockcompute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key))
	})
	return _c
}

func (_c *mockcompute_Get_Call) Return(entry *domain.Entry, err error) *mockcompute_Get_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *mockcompute_Get_Call) RunAndReturn(run func(ctx context.Context, key domain.Key) (*domain.Entry, error)) *mockcompute_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type mockcompute
func (_mock *mockcompute) Set(ctx context.Context, key domain.Key, value domain.Value) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Key, domain.Value) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcompute_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockcompute_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *mockcompute_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *mockcompute_Set_Call {
	return &mockcompute_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *mockcompute_Set_Call) Run(run func(ctx context.Context, key domain.Key, value domain.Value)) *mockcompute_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Key), args[2].(domain.Value))
	})
	return _c
}

func (_c *mockcompute_Set_Call) Return(err error) *mockcompute_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcompute_Set_Call) RunAndReturn(run func(ctx context.Context, key domain.Key, value domain.Value) error) *mockcompute_Set_Call {
	_c.Call.Return(run)
	return _c
}
